name: default

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build image
        run: |
          echo ${{ vars.GETHUB_SHA }}
          SHORT_SHA= ${{ vars.GITHUB_SHA }} | cut -c1-7
          make build-image TAG_NAME="$SHORT_SHA"
      - name: push image
        run: docker push TAG_NAME="$SHORT_SHA"

