name: default

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build image
        run: |
          echo "${{ github.sha }}"
          make build-image TAG_NAME="${{ github.sha }}"
      - name: push image
        run: docker push TAG_NAME="${{ github.sha }}"

