name: default

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build image
        run: |
          echo "${{ vars.JOB_NAME }}"
          echo "${{ vars.GITHUB_SHA }}"
          make build-image TAG_NAME="${{ vars.GITHUB_SHA }}"
      - name: push image
        run: docker push TAG_NAME="$SHORT_SHA"

